### ISSUE TITLE
Bookcreator plugin

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [selfthinker/dokuwiki_template_writr#1]
In combination with the bookcreator plugin, besides the icon "Z" for adding a page to the book a text appears below all the other icons for editing, history and so on:
![fehler](https://cloud.githubusercontent.com/assets/1800472/8201842/f1a8325e-14d4-11e5-8f49-f05cdcc2da93.png)

Regards
Juergen

**Comment by selfthinker** [comment]
This happens with any plugin which adds an item to the page tools, so e.g. also the DW2PDF and ODT plugins.
This is a more complicated issue and would ideally need some more radical changes in the core. But I found a relatively quick and easy solution. I will fix this by just displaying the link text without an icon and in normal text size. That's not exactly pretty but at least functional.
In the long term this should be fixed in the core.
