### ISSUE TITLE
TEMPLATE_PAGETOOLS_DISPLAY event not supported

### ISSUE THREAD

**Issue by berho** [selfthinker/dokuwiki_template_writr#5]
Thanks for the wunderfull template! It looks good and work on several screen sizes perfect (smartphone, tablet, desktop)!

I am using the [move plugin](https://www.dokuwiki.org/plugin:move) which extend the page tools menu. The template have to support the TEMPLATE_PAGETOOLS_DISPLAY event to implement this. It would be great if you can add this functionality.

Thanks

**Comment by mightymt** [comment]
The *writr* template already has support for TEMPLATE_PAGETOOLS_DISPLAY, works as expected (e.g. with the *dw2pdf* plugin). 
The problem is that the *move* plugin (for whatever reason) only adds the toolbar link/button if you use one of the following templates: 'dokuwiki', 'arago', 'bootstrap3'. Here's a related issue I found: michitux/dokuwiki-plugin-move#27

**Comment by selfthinker** [comment]
Yes, this seems to be an issue with the move plugin.
This has also a lot to do with the way those template events have been implemented in the core.
